Repository bunderLikeLion/sellon_frontend, pull requests merged in 2022-08, with the labels that each got.

#23 Witdrawl
  src/apis/config.js
  src/components/MyPage/ProfileBackground/ProfileBackground.js
  src/components/Navbar/UserRelatedDropDown.js
  src/queries/auth/useLoginMutation.js
  src/queries/auth/useWithdrawlMutation.js
Labels: enhancement

#28 Inventory UI
  src/components/MyPage/ItemList.js
  src/components/MyPage/ItemListCard.js
  src/components/MyPage/ProfileBackground/ProfileBackground.js
Labels: enhancement

#29 feat:LoginUI생성
  src/pages/Login/Login.js
Labels: enhancement

#31 update Register UI
  src/pages/Login/Login.js
  src/pages/Register/Register.js
Labels: enhancement

#34 style: 관심 거래 기본 카드 UI 추가;
  src/components/MyPage/InterestedAuctionList.js
  src/components/MyPage/InterestedAuctionListCard.js
  src/components/MyPage/ItemListCard.js
  src/components/MyPage/TabBar.js
Labels: enhancement

#33 FEAT: itemDetail.js 생성 및 UI 작업
  src/App.js
  src/pages/MyPage/ItemDetail.js
Labels: enhancement

#39 Auction detail
  src/App.js
  src/components/Auction/AuctionDetail/AuctionItem.js
  src/components/Auction/AuctionDetail/AuctionMySuggestion.js
  src/components/Auction/AuctionDetail/AuctionOtherSuggestion.js
  src/components/Auction/AuctionDetail/AuctionOtherSuggestionItem.js
  src/components/Auction/AuctionDetail/ValidationModal.js
  src/components/MyPage/ItemListCard.js
  src/pages/Auction/Auction.js
  src/pages/AuctionDetail/AuctionDetail.js
Labels: enhancement

#41 Crate homeground UI
  src/components/Home/HomeAuctionListCard.js
  src/pages/Home/Home.js
Labels: enhancement

#45 Add item
  src/App.js
  src/apis/productsRelatredAPI.js
  src/components/MyPage/AddItemModal.js
  src/components/MyPage/InterestedAuctionListCard.js
  src/components/MyPage/InterestedAuctionListCardFinished.js
  src/components/MyPage/TabBar.js
  src/components/MyPage/TransactionHistory.js
  src/hooks/useInput.js
  src/queries/product/useCategoryQuery.js
  src/queries/product/useCreateProductMutation.js
Labels: enhancement

#47 FEAT: NewAuction.js 생성 및 UI 작업
  src/App.js
  src/pages/Auction/NewAuction1.js
  src/pages/Auction/NewAuction2.js
Labels: enhancement

#51 App fix
  src/App.js
Labels: bug

#42 feat:AuctionFinished.js ui 초안 작성
  package-lock.json
  package.json
  sample_env
  src/App.js
  src/pages/Auction/AuctionFinished.js
Labels: documentation

#53 feat: get my products logic finished
  src/App.js
  src/apis/productsRelatredAPI.js
  src/components/MyPage/ItemList.js
  src/components/MyPage/ItemListCard.js
  src/queries/auth/useLoginMutation.js
  src/queries/auth/useSignInMutation.js
  src/queries/product/useMyProductsQuery.js
  src/styles/globalStyles.js
Labels: enhancement

#62 Auction publish Modal
  src/App.js
  src/components/Auction/AuctionDetail/ValidationModal.js
  src/components/Auction/AuctionPublish/AuctionPublishModal.js
  src/components/Auction/AuctionPublish/InventoryItem.js
  src/pages/AuctionPublish/NewAuction1.js
  src/pages/AuctionPublish/NewAuction2.js
  src/pages/Home/Home.js
  src/pages/Login/Login.js
  src/pages/Register/Register.js
Labels: enhancement

#61 REFACTOR: Home.js 코드 리팩토링
  src/components/Home/HomeAuctionListCard.js
  src/pages/Home/Home.js
Labels: enhancement

#64 feat: Create ItemDetail_UI
  src/components/MyPage/ItemDetail/Left_Component.js
  src/components/MyPage/ItemDetail/Right_Component.js
  src/pages/MyPage/ItemDetail.js
Labels: enhancement

#65 Home UI
  src/components/Home/HomeAuctionListCard.js
  src/pages/Home/Home.js
Labels: enhancement

#66 Auction details
  src/components/Auction/AuctionDetail/AuctionItem.js
  src/components/Auction/AuctionDetail/AuctionMySuggestion.js
  src/components/Auction/AuctionDetail/AuctionOtherSuggestion.js
  src/components/Auction/AuctionDetail/AuctionOtherSuggestionItem.js
  src/pages/AuctionDetail/AuctionDetail.js
  src/themes/theme.js
Labels: enhancement

#69 REFACTOR: ItemDetial.js 코드 리팩토링
  src/components/MyPage/ItemDetail/Left_Component.js
  src/components/MyPage/ItemDetail/Right_Component.js
  src/pages/MyPage/ItemDetail.js
Labels: enhancement

#71 axios instance request interceptor 추가 및 코드 정리
  src/App.js
  src/apis/config.js
  src/apis/productsRelatredAPI.js
  src/apis/userRelatedAPI.js
  src/components/MyPage/ItemDetail/Left_Component.js
  src/components/Navbar/UserRelatedDropDown.js
  src/hooks/index.js
  src/hooks/useExpirHandler.js
  src/pages/MyPage/ItemDetail.js
  src/queries/auth/useLoginMutation.js
  src/queries/auth/useWithdrawlMutation.js
Labels: bug, enhancement

#70 REFACTOR: Chat.js UI코드 리팩토링
  src/components/MyPage/Chat/ChatLists.js
  src/components/MyPage/Chat/InputMessage.js
  src/components/MyPage/Chat/OnChatUserProfile.js
  src/pages/Chat/Chat.js
Labels: enhancement

#73 New auction refactor
  src/pages/AuctionPublish/NewAuction1.js
  src/pages/AuctionPublish/NewAuction2.js
Labels: enhancement

#74 netlify 배포
  .gitignore
  public/index.html
  yarn.lock
Labels: good first issue

#75 Netlify 관련 설정 추가
  README.md
  public/_redirects
  public/index.html
Labels: good first issue

#77 feat: Create LegendTown
  src/components/TopRank/Champion.js
  src/components/TopRank/ExchangeRanking.js
  src/components/TopRank/MostExchanger.js
  src/components/TopRank/Ranking.js
  src/components/TopRank/TierRise.js
  src/components/TopRank/TierRiseProfile.js
  src/components/TopRank/TopRanker.js
  src/components/TopRank/TotalExchange.js
  src/components/TopRank/WeeklyStatus.js
  src/pages/TopRank/TopRank.js
Labels: enhancement

#85 REFACTOR: AddItemModal.js UI코드 리팩토링
  src/components/MyPage/AddItemModal.js
  src/components/MyPage/ItemAddForm/ImageDragDrop/styles.js
Labels: enhancement

#76 feat:TransactionHistory.js UI 작업
  package-lock.json
  package.json
  src/components/MyPage/TransactionHistory.js
  src/images/nike_jordan.jpg
Labels: enhancement

#88 feat: 네브바 UI 작성
  src/components/Navbar/UserRelatedDropDown.js
  src/pages/Navbar/Navbar.js
Labels: enhancement

#90 수정사항 추가
  package-lock.json
  src/components/TopRank/WeeklyStatus.js
  yarn.lock
Labels: enhancement

#91 feature: mypage 히스토리 없는 경우 component 작성, TabBar 반영
  src/components/MyPage/NoTransactionHistory.js
  src/components/MyPage/TabBar.js
  src/components/MyPage/TransactionHistory.js
  src/images/nike_jordan.jpg
Labels: enhancement

#93 feat: Login UI, Register UI 생성
  src/images/Sign_Img.jpeg
  src/pages/Login/Login.js
  src/pages/Register/Register.js
Labels: enhancement

#94 Auction auctioneer
  src/App.js
  src/components/Auction/AuctionAuctioneer/ByerSingleBox.js
  src/components/Auction/AuctionAuctioneer/ItemDetailContainer.js
  src/components/Auction/AuctionAuctioneer/ItemImageContainer.js
  src/pages/AuctionAuctioneer/Auctioneer.js
Labels: enhancement

#98 feat: Login, Register Card UI 및 Input width 수정
  src/components/MyPage/ItemDetail/Left_Component.js
  src/components/MyPage/ItemDetail/Right_Component.js
  src/components/TopRank/Ranking.js
  src/components/TopRank/TopRanker.js
  src/components/TopRank/WeeklyStatus.js
  src/components/TopRank/index.js
  src/pages/Chat/Chat.js
  src/pages/Login/Login.js
  src/pages/Register/Register.js
  src/pages/TopRank/TopRank.js
Labels: enhancement

#101 refactor: css code refactoring
  src/components/Auction/AuctionAuctioneer/ByerSingleBox.js
  src/components/Auction/AuctionAuctioneer/ItemDetailContainer.js
  src/components/Auction/AuctionAuctioneer/ItemImageContainer.js
  src/components/Auction/AuctionDetail/InventoryCards/HiddenCard.js
  src/components/Auction/AuctionDetail/MySuggested.js
  src/components/Auction/AuctionDetail/MySuggesting.js
  src/components/Auction/AuctionDetail/ValidationModal.js
  src/components/Auction/AuctionPublish/AuctionPublishModal.js
  src/components/Home/HomeAuctionListCard.js
  src/components/MyPage/AddItemModal.js
  src/components/MyPage/Chat/ChatLists.js
  src/components/MyPage/Chat/ChatMessages.js
  src/components/MyPage/Chat/InputMessage.js
  src/components/MyPage/Chat/MyProfile.js
  src/components/MyPage/Chat/OnChatUserProfile.js
  src/components/MyPage/InterestedAuctionListCard.js
  src/components/MyPage/InterestedAuctionListCardFinished.js
  src/components/MyPage/ItemAddForm/ImageDragDrop/styles.js
  src/components/MyPage/ItemDetail/Left_Component.js
  src/components/MyPage/ItemList.js
  src/components/MyPage/ItemListCard.js
  src/components/MyPage/NoTransactionHistory.js
  src/components/Navbar/UserRelatedDropDown.js
  src/components/TopRank/TopRanker.js
  src/components/TopRank/WeeklyStatus.js
  src/pages/Auction/AuctionFinished.js
  src/pages/AuctionAuctioneer/Auctioneer.js
  src/pages/AuctionPublish/NewAuction1.js
  src/pages/AuctionPublish/NewAuction2.js
  src/pages/Chat/Chat.js
  src/pages/Home/Home.js
  src/pages/Login/Login.js
  src/pages/MyPage/ItemDetail.js
  src/pages/Register/Register.js
Labels: enhancement

#103 feat: ValidationModal UI 수정
  src/components/Auction/AuctionDetail/ValidationModal.js
Labels: enhancement

#104 feat: ItemDetail UI 수정
  package-lock.json
  package.json
  src/components/MyPage/Chat/ChatLists.js
  src/components/MyPage/Chat/UserEvaluationModal.js
  src/components/MyPage/ItemDetail/ItemImage.js
  src/components/MyPage/ItemDetail/ItemInfoContainer.js
  src/components/MyPage/ItemDetail/UserInformation.js
  src/pages/AuctionPublish/NewAuction1.js
  src/pages/MyPage/ItemDetail.js
  yarn.lock
Labels: enhancement

#105 feat: 유저 평가 UI 생성
  src/components/MyPage/Chat/UserEvaluationModal.js
  src/components/MyPage/ItemDetail/Left_Component.js
  src/themes/theme.js
Labels: enhancement

#108 feat: FilterModal.js 수정
  src/components/Home/FilterModal.js
  src/components/Home/HomeAuctionListCard.js
  src/components/MyPage/Chat/UserEvaluationModal.js
  src/components/MyPage/ItemDetail/ItemImage.js
  src/components/MyPage/ItemDetail/ItemInfoContainer.js
  src/components/MyPage/ItemDetail/UserInformation.js
  src/pages/Auction/Auction.js
  src/pages/MyPage/ItemDetail.js
  src/pages/Navbar/Navbar.js
  src/pages/TopRank/TopRank.js
  src/themes/theme.js
Labels: enhancement

#109 feat: NewAuction UI 수정
  src/components/Auction/AuctionPublish/AuctionPublishModal.js
  src/components/Auction/AuctionPublish/InventoryItem.js
  src/components/MyPage/ItemDetail/ItemImage.js
  src/components/NewAuction/InfoContainerWithItem.js
  src/components/NewAuction/NewAuctionInput.js
  src/pages/NewAuction/NewAuction.js
  src/themes/theme.js
Labels: enhancement

#112 style: navbar 수정 및 홈그라운드 수정
  src/components/MyPage/Chat/InputMessage.js
  src/components/MyPage/Chat/MyProfile.js
  src/components/MyPage/Chat/UserEvaluationModal.js
  src/components/Navbar/UserRelatedDropDown.js
  src/pages/Auction/Auction.js
  src/pages/Chat/Chat.js
  src/pages/MyPage/UserInfoChange.js
Labels: enhancement

#115 Navbar
  src/App.js
  src/components/MyPage/Chat/ChatLists.js
  src/components/MyPage/Chat/UserEvaluationModal.js
  src/components/MyPage/Chat/UserInfoDetailModal.js
  src/components/Navbar/UserRelatedDropDown.js
  src/pages/MyPage/UserInfoChange.js
  src/pages/Register/Register.js
Labels: enhancement

#113 feat: 마이페이지-관심거래 UI 작성
  src/components/MyPage/InterestedAuctionList.js
  src/components/MyPage/InterestedAuctionListCard.js
  yarn.lock
Labels: enhancement

#116 chore: dropdownmenu 및 오류수정
  src/components/Navbar/UserRelatedDropDown.js
Labels: enhancement

#114 UI refactor
  src/App.js
  src/components/Auction/AuctionDetail/AuctionDetailModal.js
  src/components/Auction/AuctionDetail/InventoryCard.js
  src/components/Auction/AuctionDetail/ValidationModal.js
  src/components/Home/HomeAuctionListCard.js
  src/components/MyPage/ItemDetail/ItemInfoContainer.js
  src/components/MyPage/MyAuctionList.js
  src/components/MyPage/TabBar.js
  src/components/Navbar/UserRelatedDropDown.js
  src/pages/Auction/AuctionFinished.js
  src/pages/Navbar/Navbar.js
  src/styles/StyledComponetStyles.js
Labels: enhancement

#117 chore: card 배열 justify-content 수정
  src/components/MyPage/InterestedAuctionListCard.js
Labels: enhancement

#118 Toprank refactor, Auctioneer 기능 추가, input 자동완성 배경 투명처리
  package-lock.json
  src/components/Auction/AuctionAuctioneer/BuyerSingleBox.js
  src/components/Auction/AuctionAuctioneer/DiscardMessageModal.js
  src/components/Auction/AuctionAuctioneer/ItemDetailContainer.js
  src/components/Auction/AuctionAuctioneer/ItemImageContainer.js
  src/components/Auction/AuctionAuctioneer/SelectMessageModal.js
  src/components/Home/FilterModal.js
  src/components/MyPage/AddItemModal.js
  src/components/MyPage/InterestedAuctionListCard.js
  src/components/TopRank/Ranking.js
  src/components/TopRank/TopRanker.js
  src/components/TopRank/WeeklyStatus.js
  src/pages/AuctionAuctioneer/Auctioneer.js
  src/pages/TopRank/TopRank.js
  yarn.lock
Labels: enhancement

#119 feat: 마이페이지-내가 올린 경매 UI 작성
  src/components/MyPage/InterestedAuctionListCard.js
  src/components/MyPage/MyAuctionList.js
Labels: enhancement

#120 User info change
  src/components/MyPage/ItemListCard.js
  src/components/MyPage/TransactionHistory.js
Labels: enhancement

#121 feat: 명예의전당-이번주 신분상승UI 수정 및 추가
  src/components/TopRank/WeeklyStatus.js
Labels: enhancement

#122 User info change
  src/components/Home/HomeAuctionListCard.js
  src/components/MyPage/MyAuctionList.js
  src/pages/Auction/Auction.js
Labels: enhancement

#123 feat: 명예의전당 물음표 아이콘 tooltip UI
  src/components/TopRank/Ranking.js
  src/components/TopRank/TopRanker.js
  src/components/TopRank/WeeklyStatus.js
Labels: enhancement

#125 Chat
  src/components/MyPage/TabBar.js
  src/components/Navbar/UserRelatedDropDown.js
  src/pages/Chat/Chat.js
Labels: enhancement

#130 Auction pagination
  src/components/MyPage/TransactionHistory.js
  src/pages/Auction/Auction.js
Labels: enhancement

#128 feat: 마이페이지-히스토리 Pagination
  src/components/MyPage/TransactionHistory.js
Labels: enhancement

#134 feat: AuctionDetail 모달 UI 배열
  src/components/Auction/AuctionDetail/AuctionDetailModal.js
  src/components/MyPage/ItemDetail/ItemImage.js
  src/components/MyPage/ItemDetail/ItemInfoContainer.js
Labels: enhancement

#136 feat : Auction Detail Reafactor
  src/components/Auction/AuctionDetail/AuctionItem.js
  src/components/Auction/AuctionDetail/AuctionOtherSuggestion.js
  src/components/Auction/AuctionDetail/MySuggested.js
  src/components/MyPage/ItemListCard.js
  src/components/MyPage/TransactionHistory.js
  src/layouts/WrapContainer.js
  src/pages/Auction/Auction.js
Labels: enhancement

#135 홈그라운드 필터 UI
  src/components/Home/FilterModal.js
  src/pages/Auction/Auction.js
  src/pages/Register/Register.js
Labels: enhancement

#137 빈 목록에 대해서 공통적으로 사용할 수 있는 공통 컴포넌트 추가
  src/components/Shared/EmptyListPlaceholder.js
  src/pages/AuctionAuctioneer/Auctioneer.js
Labels: enhancement

#141 refactor: 아이템 추가 모달창 UI 리팩토링 완료
  src/components/MyPage/AddItemModal.js
  src/components/MyPage/ItemAddForm/ImageDragDrop/styles.js
Labels: enhancement

#139 0815 디자인 추가 개선
  src/components/MyPage/InterestedAuctionList.js
  src/components/MyPage/ItemList.js
  src/components/MyPage/MyAuctionList.js
  src/components/MyPage/TabBar.js
  src/components/MyPage/TransactionHistory.js
  src/components/Shared/AuctionListItem.js
  src/components/TopRank/Ranking.js
  src/components/TopRank/TopRanker.js
  src/components/TopRank/WeeklyStatus.js
  src/pages/Auction/Auction.js
  src/pages/Navbar/Navbar.js
  src/pages/TopRank/TopRank.js
Labels: enhancement

#145 feat: Code refactor
  src/components/Auction/AuctionPublish/AuctionPublishModal.js
  src/components/MyPage/AddItemModal.js
  src/components/NewAuction/InfoContainerWithItem.js
  src/components/NewAuction/NewAuctionInput.js
  src/components/TopRank/Ranking.js
  src/components/TopRank/TopRanker.js
  src/components/TopRank/WeeklyStatus.js
  src/pages/Auction/Auction.js
  src/pages/AuctionPublish/AuctionPublish.js
  src/pages/AuctionPublish/NewAuction1.js
  src/pages/AuctionPublish/NewAuction2.js
Labels: enhancement

#148 Chat 거래보기 UI
  src/components/Home/FilterModal.js
  src/components/MyPage/Chat/UserInfoDetailModal.js
  src/pages/Auction/Auction.js
Labels: enhancement

#150 feat: AuctionOtherSuggestion Pagination 추가 및 스타일 수정
  src/components/Auction/AuctionDetail/AuctionOtherSuggestion.js
  src/components/Auction/AuctionDetail/InventoryCard.js
  src/components/Auction/AuctionDetail/MySuggesting.js
Labels: enhancement

#157 Item detail&change refactor
  package-lock.json
  src/App.js
  src/components/MyPage/AddItemModal.js
  src/components/MyPage/ItemAddForm/ImageDragDrop/styles.js
  src/components/MyPage/ItemDetail/ItemImage.js
  src/components/MyPage/ItemDetail/ItemInfoContainer.js
  src/components/MyPage/ItemDetail/UserInformation.js
  src/components/MyPage/ItemInfoChange/ChangeItemCategory.js
  src/components/MyPage/ItemInfoChange/ChangeItemExtraImage.js
  src/components/MyPage/ItemInfoChange/ChangeItemId.js
  src/components/MyPage/ItemInfoChange/ChangeItemImage.js
  src/components/MyPage/ItemInfoChange/ChangeItemStatus.js
  src/components/MyPage/ItemInfoChange/ChangeItemTextarea.js
  src/pages/MyPage/ItemDetail.js
  src/pages/MyPage/ItemInfoChange.js
  yarn.lock
Labels: enhancement

#160 feat: About.js AcutionSlider.js Add link
  src/components/Auction/AuctionAuctioneer/ItemDetailContainer.js
  src/components/Auction/AuctionSlider.js
  src/pages/About/About.js
  src/pages/Auction/Auction.js
  src/pages/AuctionAuctioneer/Auctioneer.js
Labels: enhancement

#161 Item detail 페이지, 모달창 UI refactor
  src/components/Auction/AuctionAuctioneer/ItemDetailContainer.js
  src/components/Auction/AuctionDetail/AuctionDetailModal.js
  src/components/MyPage/ItemDetail/ItemImage.js
  src/components/MyPage/ItemDetail/ItemInfoContainer.js
  src/components/MyPage/ItemDetail/UserInformation.js
  src/components/MyPage/ItemList.js
  src/pages/MyPage/ItemDetail.js
Labels: enhancement

#162 Mypage auction chat + UI 리팩토링
  package-lock.json
  src/components/Auction/AuctionAuctioneer/ItemDetailContainer.js
  src/components/Auction/AuctionDetail/AuctionDetailModal.js
  src/components/Auction/AuctionPublish/InventoryItem.js
  src/components/MyPage/Chat/ChatLists.js
  src/components/MyPage/Chat/InputMessage.js
  src/components/MyPage/Chat/MyProfile.js
  src/components/MyPage/Chat/OnChatUserProfile.js
  src/components/MyPage/ItemDetail/ItemInfoContainer.js
  src/components/MyPage/ItemListCard.js
  src/components/NewAuction/NewAuctionInput.js
  src/components/Shared/AuctionListItem.js
  src/pages/Chat/Chat.js
  src/pages/NewAuction/NewAuction.js
  yarn.lock
Labels: enhancement

#165 feat: AuctionSlider 경매 제목 Text Overflow 조정
  src/components/Auction/AuctionSlider.js
  yarn.lock
Labels: enhancement

#164 feat: MyPage History 경매장으로 가는 Link 생성
  src/components/MyPage/TransactionHistory.js
Labels: enhancement

#168 feat: TopRank ToolTip Color 검은색으로 수정
  src/components/TopRank/TopRanker.js
Labels: enhancement

#163 feat: 마이페이지-인벤토리 align 수정
  src/components/MyPage/Chat/ChatLists.js
  src/components/MyPage/ItemInfoChange/ChangeItemCategory.js
  src/components/MyPage/ItemInfoChange/ChangeItemExtraImage.js
  src/components/MyPage/ItemInfoChange/ChangeItemId.js
  src/components/MyPage/ItemInfoChange/ChangeItemImage.js
  src/components/MyPage/ItemInfoChange/ChangeItemStatus.js
  src/components/MyPage/ItemInfoChange/ChangeItemTextarea.js
  src/components/MyPage/ItemList.js
  src/components/Shared/AuctionListItem.js
Labels: enhancement

#166 홈그라운드 필터, 유저 평가하기 버튼 수정, Auctioneer 상단 텍스트 추가
  src/components/Auction/AuctionAuctioneer/ItemImageContainer.js
  src/components/Home/FilterModal.js
  src/components/MyPage/Chat/UserEvaluationModal.js
  src/pages/Auction/Auction.js
  src/pages/AuctionAuctioneer/Auctioneer.js
  yarn.lock
Labels: enhancement

#172 refactor: NewAuction 페이지, 아이템 모달창 UI 리팩토링
  src/components/Auction/AuctionPublish/AuctionPublishModal.js
  src/components/Auction/AuctionPublish/InventoryItem.js
  src/components/MyPage/AddItemModal.js
  src/components/NewAuction/NewAuctionInput.js
  src/pages/NewAuction/NewAuction.js
Labels: enhancement

#174 style: 마이페이지-히스토리 Right Container UI 스타일 수정
  src/components/MyPage/TransactionHistory.js
Labels: enhancement

#175 feat: 마이페이지 히스토리 placeholder 컴포넌트 hover시 텍스트에 밑줄효과 추가
  src/components/MyPage/TransactionHistory.js
Labels: enhancement

#173 feat: Auction home UI refactor
  src/components/Auction/AuctionSlider.js
  src/pages/Auction/Auction.js
  src/utils/timeLimitHandler.js
Labels: enhancement

#176 Auction home refactor
  src/components/Shared/AuctionListItem.js
  src/pages/Auction/Auction.js
Labels: enhancement

#177 feat: 홈그라운드 필터 버튼 수정
  src/components/Home/FilterModal.js
  src/components/MyPage/ItemInfoChange/ChangeItemExtraImage.js
  src/components/MyPage/ItemInfoChange/ChangeItemTextarea.js
  src/pages/About/About.js
Labels: enhancement

#179 Auctioneer refactor
  src/components/Auction/AuctionAuctioneer/DiscardMessageModal.js
  src/components/Auction/AuctionAuctioneer/SelectMessageModal.js
  src/queries/dealing/useCreateDealingMutation.js
Labels: enhancement

#182 feat: New auction UI
  src/components/Auction/AuctionPublish/AuctionPublishModal.js
  src/components/MyPage/Chat/ChatLists.js
  src/components/NewAuction/InfoContainerWithItem.js
  src/pages/NewAuction/NewAuction.js
Labels: enhancement

#185 feat: 인벤토리 아이템명 hover 추가
  src/pages/MyPage/ItemDetail.js
Labels: enhancement

#184 feat: TopRank 10등 margin 조정
  src/components/TopRank/Ranking.js
  src/pages/About/About.js
  src/pages/MyPage/ItemDetail.js
Labels: enhancement

#189 feat: TopRank 평가하기, 거래보기 Modal UI 수정
  src/components/Auction/AuctionAuctioneer/ItemDetailContainer.js
  src/components/MyPage/Chat/UserEvaluationModal.js
  src/components/MyPage/Chat/UserInfoDetailModal.js
  src/pages/MyPage/ItemDetail.js
Labels: enhancement

#190 style: 경매장 홈 필터 높이 및 내부 간격 조정
  src/components/Home/FilterModal.js
  yarn.lock
Labels: enhancement

#186 feat: 아이템 정보 수정
  src/components/MyPage/AddItemModal.js
  src/components/MyPage/ItemAddForm/ImageDragDrop/styles.js
  src/components/MyPage/ItemInfoChange/ChangeItemCategory.js
  src/components/MyPage/ItemInfoChange/ChangeItemId.js
  src/components/MyPage/ItemInfoChange/ChangeItemImage.js
  src/components/MyPage/ItemInfoChange/ChangeItemStatus.js
  src/components/MyPage/ItemInfoChange/ChangeItemTextarea.js
  src/pages/MyPage/ItemInfoChange.js
Labels: enhancement

#191 chore: Auction filter 컨테이너 내부 배열 조정
  src/components/Home/FilterModal.js
Labels: enhancement

#194 Auctioneer refactor
  src/components/Auction/AuctionAuctioneer/BuyerSingleBox.js
  src/components/Auction/AuctionAuctioneer/ItemImageContainer.js
  src/components/MyPage/ItemListCard.js
  src/pages/AuctionAuctioneer/Auctioneer.js
Labels: enhancement

#192 feat: Favicon, Add Main Logo
  public/favicon.ico
  src/components/MyPage/Chat/UserEvaluationModal.js
  src/components/MyPage/Chat/UserInfoDetailModal.js
  src/images/Sellon-Logo.png
  src/pages/Navbar/Navbar.js
Labels: enhancement

#193 style: FAQ 아코디언 UI 수정
  src/components/Home/FilterModal.js
  src/pages/About/About.js
Labels: enhancement

#199 chore: 로그인 UI 수정
  src/components/Home/FilterModal.js
  src/images/LoginPic.jpeg
  src/pages/About/About.js
  src/pages/Login/Login.js
Labels: enhancement

#200 chore: 마이페이지 백그라운드 이미지 수정
  src/components/MyPage/ProfileBackground/ProfileBackground.js
  src/components/MyPage/TransactionHistory.js
  src/images/ProfileBackground.jpeg
  src/pages/Login/Login.js
Labels: enhancement

#198 style: 실시간 인기 경매 화살표 아이콘 수정
  src/components/Auction/AuctionSlider.js
  src/components/MyPage/InterestedAuctionList.js
  src/components/MyPage/ItemList.js
  src/components/MyPage/TransactionHistory.js
  src/components/Shared/EmptyListPlaceholder.js
  src/components/Shared/ValidationModal.js
Labels: enhancement

#201 style: 마이페이지 히스토리 placeholder 배경&거래횟수 숫자 배열 수정
  src/components/MyPage/InterestedAuctionList.js
  src/components/MyPage/TransactionHistory.js
  src/components/Shared/EmptyListPlaceholder.js
  src/components/Shared/ValidationModal.js
Labels: enhancement

#202 chore: 마이페이지 히스토리 수정
  src/components/MyPage/Chat/ChatMsgContainer.js
  src/components/MyPage/TransactionHistory.js
  src/components/Shared/EmptyHistoryPlaceholder.js
  src/pages/Chat/Chat.js
  src/pages/Register/Register.js
Labels: enhancement

#203 chore: 히스토리 우측 컨테이너 margin 조정
  src/components/MyPage/TransactionHistory.js
Labels: enhancement

#204 feat: 경매 상세 페이지 itemName Tooltip 추가
  src/components/Auction/AuctionDetail/AuctionItem.js
Labels: enhancement

#205 chore: 인벤토리 폰트수정
  src/components/Auction/AuctionPublish/AuctionPublishModal.js
Labels: enhancement
